#!/bin/sh
rsync -rvc --delete --exclude=node_modules --exclude=.git --exclude=.buildkite /var/lib/buildkite-agent/builds/reg-doc-1/jslabs/webrtc /var/www/webrtc

# mkdir -p /var/www/webrtc/node_modules

npm install --prefix /var/www/webrtc/webrtc

cd /var/www/webrtc/webrtc

npm run build

pm2 delete webrtc
pm2 start npm --name "webrtc" -- run start

pm2 show webrtc
